language: python
sudo: required
dist: trusty

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'

before_install:
  # Pre-install opengl
  - sudo apt update
  - sudo apt install llvm-6.0 llvm-6.0-tools llvm-6.0-dev freeglut3 freeglut3-dev git
  - mkdir mesa
  - cd mesa
  - wget ftp://ftp.freedesktop.org/pub/mesa/mesa-18.3.3.tar.gz
  - tar zxf mesa-18.3.3.tar.gz
  - cd mesa-18.3.3
  - mkdir mesa_install
  - ./configure --prefix=$PWD/mesa_install --enable-opengl --disable-gles1 --disable-gles2 --disable-va --disable-xvmc --disable-vdpau --enable-shared-glapi --disable-texture-float --enable-gallium-llvm --enable-llvm-shared-libs --with-gallium-drivers=swrast,swr --disable-dri --with-dri-drivers= --disable-egl --with-egl-platforms= --disable-gbm --disable-glx --disable-osmesa --enable-gallium-osmesa ac_cv_path_LLVM_CONFIG=llvm-config-6.0
  - make -j4
  - make install
  - export LIBRARY_PATH=$LIBRARY_PATH:"$PWD/mesa_install/lib"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$PWD/mesa_install/lib"
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:"$PWD/mesa_install/include/"
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:"$PWD/mesa_install/include/"
  - cd ../..
  - mkdir deps
  - cd deps
  - git clone https://github.com/mmatl/pyopengl.git
  - cd pyopengl
  - pip install .
  - cd ../..
  - pip install PyOpenGL_accelerate

install:
  - pip install .
    #  - pip install -q pytest pytest-cov coveralls
  - pip install pytest

script:
  #- pytest -W default --cov=ambicore tests/
  - PYOPENGL_PLATFORM=osmesa pytest -W default tests/

    #after_success:
    #  - coveralls
    #
deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: O4WWMbTYb2eVYIO4mMOVa6/xyhX7mPvJpd96cxfNvJdyuqho8VapOhzqsI5kahMB1hFjWWr61yR4+Ru5hoDYf3XA6BQVk8eCY9+0H7qRfvoxex71lahKAqfHLMoE1xNdiVTgl+QN9hYjOnopLod24rx8I8eXfpHu/mfCpuTYGyLlNcDP5St3bXpXLPB5wg8Jo1YRRv6W/7fKoXyuWjewk9cJAS0KrEgnDnSkdwm6Pb+80B2tcbgdGvpGaByw5frndwKiMUMgVUownepDU5POQq2p29wwn9lCvRucULxjEgO+63jdbZRj5fNutLarFa2nISfYnrd72LOyDfbJubwAzzAIsy2JbFORyeHvCgloiuE9oE7a9oOQt/1QHBoIV0seiawMWn55Yp70wQ7HlJs4xSGJWCGa5+9883QRNsvj420atkb3cgO8P+PXwiwTi78Dq7Z/xHqccsU0b8poqBneQoA+pUGgNnF6V7Z8e9RsCcse2gAWSZWuOK3ua+9xCgH7I7MeL3afykr2aJ+yFCoYJMFrUjJeodMX2RbL0q+3FzIPZeGW3WdhTEAL9TSKRcJBSQTskaQlZx/OcpobxS7t3d2S68CCLG9uMTqOTYws55WZ1etalA75sRk9K2MR7ZGjZW3jdtvMViISc/t6Rrjea1GE8ZHGJC6/IeLIWA2c7nc=
  distributions: sdist bdist_wheel
notifications:
  email: false
